# Generated by Django 4.2.2 on 2023-06-23 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0005_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('order',), 'verbose_name': 'Field', 'verbose_name_plural': 'Fields'},
        ),
    ]
