# Generated by Django 4.2.2 on 2023-06-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0006_alter_skill_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
        migrations.AddField(
            model_name='skill',
            name='backendname',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='skill',
            name='devopsname',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='skill',
            name='frontname',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='skill',
            name='pmname',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Name'),
        ),
    ]
