# Generated by Django 4.2.2 on 2023-06-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0007_remove_skill_name_skill_backendname_skill_devopsname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='backendname',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='backend name'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='devopsname',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='devops name'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='frontname',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='front name'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='pmname',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='pm name'),
        ),
    ]
