# Generated by Django 4.2.2 on 2023-06-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0010_alter_skill_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='percentage2',
            field=models.IntegerField(blank=True, default=50, verbose_name='Percentage2'),
        ),
    ]
