# Generated by Django 4.2.2 on 2023-06-23 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0011_skill_percentage2'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='percentage3',
            field=models.IntegerField(blank=True, default=50, verbose_name='Percentage2'),
        ),
        migrations.AddField(
            model_name='skill',
            name='percentage4',
            field=models.IntegerField(blank=True, default=50, verbose_name='Percentage2'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='percentage',
            field=models.IntegerField(blank=True, default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='percentage2',
            field=models.IntegerField(blank=True, default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage2'),
        ),
    ]
