# Generated by Django 4.2.2 on 2023-06-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0012_skill_percentage3_skill_percentage4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='percentage3',
            field=models.IntegerField(blank=True, default=50, verbose_name='Percentage3'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='percentage4',
            field=models.IntegerField(blank=True, default=50, verbose_name='Percentage4'),
        ),
    ]
