# Generated by Django 4.2.2 on 2023-06-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0013_alter_skill_percentage3_alter_skill_percentage4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='devopsname',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='percentage2',
        ),
    ]
