# Generated by Django 4.2.2 on 2023-06-23 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0014_remove_skill_devopsname_remove_skill_percentage2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='percentage3',
            field=models.IntegerField(blank=True, default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage3'),
        ),
    ]
