# Generated by Django 4.2.2 on 2023-06-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0016_experiences_alter_skill_percentage4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name=' Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('uni_name', models.CharField(blank=True, default='', max_length=254, verbose_name='Edu Name')),
                ('edu_title', models.CharField(blank=True, default='', max_length=254, verbose_name='Edu Title')),
                ('edu_location', models.CharField(blank=True, default='', max_length=254, verbose_name='Edu Location')),
                ('edustart_date', models.DateField(verbose_name='Start Date')),
                ('eduend_date', models.DateField(blank=True, default=None, null=True, verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
            },
        ),
        migrations.AlterModelOptions(
            name='experiences',
            options={'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
    ]
