# Generated by Django 4.2.2 on 2023-06-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0017_educations_alter_experiences_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name=' Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('slug', models.SlugField(blank=True, default='', max_length=254, verbose_name='Slug')),
                ('button_text', models.CharField(blank=True, default='', max_length=254, verbose_name='button text')),
                ('file', models.FileField(blank=True, default='', upload_to='documents/', verbose_name='File')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ('order',),
            },
        ),
        migrations.AlterField(
            model_name='educations',
            name='uni_name',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Uni Name'),
        ),
    ]
