# Generated by Django 4.2.2 on 2023-07-09 15:23

from django.db import migrations, models
import micurriculum.custom_storage


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0018_document_alter_educations_uni_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, default='', storage=micurriculum.custom_storage.DocumentStorage(), upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='imagesetting',
            name='file',
            field=models.ImageField(blank=True, default='', storage=micurriculum.custom_storage.ImageSettingStorage(), upload_to='', verbose_name='Image'),
        ),
    ]
